# Generated by Django 2.2.5 on 2019-09-26 15:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_auto_20190925_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='aisdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vesseltype', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=256)),
                ('speed', models.IntegerField()),
                ('course', models.IntegerField()),
                ('heading', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
